### ISSUE TITLE
[Bug]: It is not compatible with mesa-git

### ISSUE THREAD

**Issue by laichiaheng** [luisbocanegra/plasma-smart-video-wallpaper-reborn#104]
I have:

- [x] Searched if this issue hasn't been reported yet.
- [x] Verified that I am using the latest version (*Wallpaper settings* > *top right corner for version 1.0.0 and later*), **should be the same as [https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/latest)**

Install method used:

- [x] Using Plasma's "Add new widget" (KDE Store)
- [ ] AUR
- [ ] Manually from the latest source code

**Describe the bug**

![Image](https://github.com/user-attachments/assets/1bcef54a-6af2-4a57-ba4c-e124fcf928ec)

**Steps to reproduce**

1. Install mesa-git

**Observed Result**
Many green lines.

**Expected Result**
Normal

**Screenshots/Video**
![Image](https://github.com/user-attachments/assets/1bcef54a-6af2-4a57-ba4c-e124fcf928ec)

**System information (please complete the following):**

Run `kinfo` on a terminal and paste the output bellow

```yaml
# Operating System: Arch Linux 
KDE Plasma Version: 6.3.3
KDE Frameworks Version: 6.12.0
Qt Version: 6.8.2
Kernel Version: 6.13.8-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 3700X 8-Core Processor
Memory: 31.2 GiB of RAM
Graphics Processor: AMD Radeon RX 6750 XT
```

- Things in your system that might be relevant: [e.g. Kwin scripts, Themes, Addons]

**Additional context**

**Comment by luisbocanegra** [comment]
Please report this to Qt/AMD, it's very unlikely that this plugin is doing something special to cause that bug.

**Comment by luisbocanegra** [comment]
Check if this test file produces the same https://gist.github.com/luisbocanegra/cb758ee5f57a9e7c2838b1db349b635a

**Comment by laichiaheng** [comment]
> Check if this test file produces the same https://gist.github.com/luisbocanegra/cb758ee5f57a9e7c2838b1db349b635a

Yes, the same.

**Comment by luisbocanegra** [comment]
Please report this to mesa and link the report here if you do

**Comment by laichiaheng** [comment]
https://gitlab.freedesktop.org/mesa/mesa/-/issues/12909

**Comment by luisbocanegra** [comment]
Due to the influx of duplicates I am reopening this one for visibility, also partially quoting myself from https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues/123#issuecomment-2875518734:

According to the mesa report this turned out to be a Qt bug https://codereview.qt-project.org/c/qt/qtmultimedia/+/636730 but the fix hasn't been merged yet.

You could try either of these workarounds to see if the problem goes away

https://gitlab.freedesktop.org/mesa/mesa/-/issues/12909#note_2847427
> Only happens with the ffmpeg QtMultimedia plugin (QT_MEDIA_BACKEND=ffmpeg), with gstreamer it works correctly.
AMD_DEBUG=notiling fixes it, looks like Qt bug.

**Comment by bronco74** [comment]
So? We have to wait for an update?

**Comment by luisbocanegra** [comment]
Yes or try the workarounds for now

**Comment by bronco74** [comment]
The workarounds don't work on my side and now when i enable a video the plasma shell restarts! Lol.

**Comment by laichiaheng** [comment]
The workaround works for me.

**Comment by bronco74** [comment]
@luisbocanegra  Can't you make it to work without being so dependent on mesa? Or else this problem will be coming back every time mesa updates!

**Comment by luisbocanegra** [comment]
> @luisbocanegra  Can't you make it to work without being so dependent on mesa? Or else this problem will be coming back every time mesa updates!

Unfortunately I can't with the current implementation that depends on Qt Multimedia, maybe with a C++ mpv plugin like the wallpaper engine wallpaper plugin. Have you tried that? It has an option to use mpv as backend for video wallpapers and it probably works better than the Qt implementation

**Comment by Yopioko** [comment]
Using plugin wallpaper engine for kde,same result,i dont think its problem with code 

![Image](https://github.com/user-attachments/assets/3eb06e4d-d3cf-4b8b-a3d1-2b905f3496b5)

**Comment by Yopioko** [comment]
for now recommended fix that worked for me: downgrading mesa to 25.0.2
 maybe to any version that is lower 25.1.0

**Comment by bronco74** [comment]
@luisbocanegra, I am going to try to make it work with qmplay2.  I don't like vlc and mpv!

**Comment by TheFlomax** [comment]
Hey same issu here with mesa 1:25.1.1-3

![Image](https://github.com/user-attachments/assets/47d529f2-7f60-4d16-aec8-b19291515615)

**Comment by TheFlomax** [comment]
> I am working on a version what will add support for [MpvQt](https://invent.kde.org/libraries/mpvqt) in the hopes that it will reduce these kind of problems.
> 
> Will let you know when I have a usable branch to test.
> 
> Thanks for your patience


All right, thank you for keeping this project going ❤️

In the meantime, the downgrade to mesa 25.0.2 solves the display problems.

**Comment by luisbocanegra** [comment]
Hi again, pushed the current changes to https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/tree/mpvqt-plugin branch, **very experimental**. It adds an optional C++ plugin so manual compilation is needed to be able to use the new MpvQt backend

If someone wants to test it, please follow these instructions https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/tree/mpvqt-plugin?tab=readme-ov-file#manually-from-source 

**Again, still very experimental and not all features work, e.g cross-fade is broken**

![Image](https://github.com/user-attachments/assets/3a8fe614-67a4-450a-8af3-a3b8aef4a7b5)

**Comment by Yopioko** [comment]
> Hi again, pushed the current changes to [mpvqt-plugin](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/tree/mpvqt-plugin) branch, **very experimental**. It adds an optional C++ plugin so manual compilation is needed to be able to use the new MpvQt backend
> 
> If someone wants to test it, please follow these instructions https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/tree/mpvqt-plugin?tab=readme-ov-file#manually-from-source
> 
> **Again, still very experimental and not all features work, e.g Crossfade is broken**
> 
> ![Image](https://github.com/user-attachments/assets/3a8fe614-67a4-450a-8af3-a3b8aef4a7b5)

I installed manually with install.sh and i dont have any options as in screenshot :

![Image](https://github.com/user-attachments/assets/399db1c5-bf3d-4aad-8a6b-d79b7cbf1d22)

Here is logs of install.sh:
 ./install.sh
-- The C compiler identification is GNU 15.1.1
-- The CXX compiler identification is GNU 15.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Plugin Id: luisbocanegra.smart.video.wallpaper.reborn
Version: 2.3.0
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
-- Performing Test HAVE_STDATOMIC
-- Performing Test HAVE_STDATOMIC - Success
-- Found WrapAtomic: TRUE
-- Found OpenGL: /usr/lib/libOpenGL.so
-- Found WrapOpenGL: TRUE
-- Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR) 
Installing in /home/yopi/.local. Run /home/yopi/plasma-smart-video-wallpaper-reborn/build/prefix.sh to set the environment for plasma-smart-video-wallpaper-reborn.
-- Could NOT find WrapVulkanHeaders (missing: Vulkan_INCLUDE_DIR) 
-- Found X11: /usr/include
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Configuring done (1.2s)
-- Generating done (0.0s)
-- Build files have been written to: /home/yopi/plasma-smart-video-wallpaper-reborn/build
-- Install configuration: ""
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/config
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/config/main.xml
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/icons
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/icons/matrix_logo.svg
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/components
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/components/CheckableValueListView.qml
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/components/Header.qml
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/VideoPlayer.qml
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/EffectsModel.qml
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/ScreenModel.qml
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/main.qml
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/RunCommand.qml
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/DBusFallback.qml
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/DBusPrimary.qml
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/FadePlayer.qml
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/DBusMethodCall.qml
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/DBusSignalMonitor.qml
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/TasksModel.qml
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/code
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/code/utils.js
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/code/enum.js
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/tools
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/tools/gdbus_get_signal.sh
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/contents/ui/config.qml
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/translate
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/translate/template.pot
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/translate/ReadMe.md
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/translate/el_GR.po
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/translate/ru.po
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/translate/pt_BR.po
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/translate/nl.po
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/translate/es.po
-- Installing: /home/yopi/.local/share/plasma/wallpapers/luisbocanegra.smart.video.wallpaper.reborn/metadata.json
-- Installing: /home/yopi/.local/share/metainfo/luisbocanegra.smart.video.wallpaper.reborn.appdata.xml

**Comment by luisbocanegra** [comment]
@Yopioko it seems you didn't install from the right branch mpvqt-plugin

**Comment by Yopioko** [comment]
> [@Yopioko](https://github.com/Yopioko) it seems you didn't install from the right branch mpvqt-plugin

mb,installed from right branch,works perfectly ! 
screenshot:

![Image](https://github.com/user-attachments/assets/8c83a459-21f7-4b5a-b8f4-b0dad63f1a4c)

**Comment by luisbocanegra** [comment]
I have no idea if mpvqt supports it, I don't have an HDR monitor to test that. Do you have to enable some setting with plain mpv or does it work automagically?

**Comment by TheFlomax** [comment]
> Okay, thank you. mpvqt can read mpv configuration from `$HOME/.config/mpvqt/mpvqt.conf` can you try adding these options there and restarting plasmashell (`systemctl --user restart plasma-plasmashell.service`) to see if HDR works?

Hey, I didn't really understand how you want me to integrate these options.

In any case, with the mpvqt-plugin build and my screen in HDR mode, there are no problems or graphical issues.

![Image](https://github.com/user-attachments/assets/1459bab2-692e-443a-be13-52879f553dbd)

**Comment by luisbocanegra** [comment]
> > Okay, thank you. mpvqt can read mpv configuration from `$HOME/.config/mpvqt/mpvqt.conf` can you try adding these options there and restarting plasmashell (`systemctl --user restart plasma-plasmashell.service`) to see if HDR works?
> 
> Hey, I didn't really understand how you want me to integrate these options.
> 
> In any case, with the mpvqt-plugin build and my screen in HDR mode, there are no problems or graphical issues.
> 
> [Image](https://github.com/user-attachments/assets/1459bab2-692e-443a-be13-52879f553dbd)

See https://mpv.io/manual/stable/#putting-command-line-options-into-the-configuration-file

tl;dr (probably, as I can't test) just add these settings that @laichiaheng suggested

```
vo=gpu-next
target-colorspace-hint=auto
```
or
```
vo=dmabuf_wayland
```

The config file does work, I tested myself by adding `osd-level=2` and it shows the video duration progress at the top of the video as you can see in https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues/104#issuecomment-2923751724

**Comment by luisbocanegra** [comment]
> In any case, with the mpvqt-plugin build and my screen in HDR mode, there are no problems or graphical issues.

But is it playing in HDR?

**Comment by TheFlomax** [comment]
> > In any case, with the mpvqt-plugin build and my screen in HDR mode, there are no problems or graphical issues.
> 
> But is it playing in HDR?

Yes, I think, because when I activate HDR into KDE Settings my screen switch into a special mode name "HDR".
So I think everything's is rending with an HDR profile.

**Comment by luisbocanegra** [comment]
I mean, shouldn't HDR videos look more vibrant or something when playing in HDR capable player+monitor? Compared to playing a regular non hdr mode, that's how you would tell if it's really working I guess

**Comment by TheFlomax** [comment]
> > > Okay, thank you. mpvqt can read mpv configuration from `$HOME/.config/mpvqt/mpvqt.conf` can you try adding these options there and restarting plasmashell (`systemctl --user restart plasma-plasmashell.service`) to see if HDR works?
> > 
> > 
> > Hey, I didn't really understand how you want me to integrate these options.
> > In any case, with the mpvqt-plugin build and my screen in HDR mode, there are no problems or graphical issues.
> > [Image](https://github.com/user-attachments/assets/1459bab2-692e-443a-be13-52879f553dbd)
> 
> See https://mpv.io/manual/stable/#putting-command-line-options-into-the-configuration-file
> 
> tl;dr (probably, as I can't test) just add these settings that [@laichiaheng](https://github.com/laichiaheng) suggested
> 
> ```
> vo=gpu-next
> target-colorspace-hint=auto
> ```
> 
> or
> 
> ```
> vo=dmabuf_wayland
> ```
> 
> The config file does work, I tested myself by adding `osd-level=2` and it shows the video duration progress at the top of the video as you can see in [#104 (comment)](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues/104#issuecomment-2923751724)


I tried adding osd-level=2 to check if the configuration file was being taken into account, and indeed, the video duration progress appeared at the top.

However, I didn’t notice any change in the colors, so I assume that KDE and my screen are already rendering in HDR.

**Comment by TheFlomax** [comment]
> I mean, shouldn't HDR videos look more vibrant or something when playing in HDR capable player+monitor? Compared to playing a regular non hdr mode, that's how you would tell if it's really working I guess

Ah, but compared to my secondary screen, they are. It’s not a huge difference, but you can definitely see the color depth.

By the way, if I go into my monitor’s settings, I can clearly see that KDE has activated HDR on my screen.

![Image](https://github.com/user-attachments/assets/fa9bcb85-b401-4441-99cf-11381995cacf)

**Comment by luisbocanegra** [comment]
Try what @laichiaheng suggested with mpv and a HDR video https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues/104#issuecomment-2936328852

From a quick search I found https://4kmedia.org/samsung-travel-with-my-pet-hdr-uhd-4k-demo/ you can try playing that sample on both mpv and the desktop and _I think_ you should be able to tell

**Comment by TheFlomax** [comment]
> Try what [@laichiaheng](https://github.com/laichiaheng) suggested with mpv and a HDR video [#104 (comment)](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/issues/104#issuecomment-2936328852)
> 
> From a quick search I found https://4kmedia.org/samsung-travel-with-my-pet-hdr-uhd-4k-demo/ you can try playing that sample on both mpv and the desktop and _I think_ you should be able to tell

So, I tried what you sent me, but unfortunately I can’t open it with the program because the format is .ts. However, when I compare on my HDR screen between MPV and VLC—so MPV with HDR color settings and VLC without—the difference in color rendering is clear! On VLC it looks very dull, while on MPV the colors are vivid and rich.

**Comment by luisbocanegra** [comment]
> So, I tried what you sent me, but unfortunately I can’t open it with the program because the format is .ts.

Select all files in the file picker:

![Image](https://github.com/user-attachments/assets/2968662a-23a1-4282-b570-f30009f8e263)

**Comment by TheFlomax** [comment]
> > So, I tried what you sent me, but unfortunately I can’t open it with the program because the format is .ts.
> 
> Select all files in the file picker:
> 
> ![Image](https://github.com/user-attachments/assets/2968662a-23a1-4282-b570-f30009f8e263)

Hum... Do you see any diff ? 
https://kdrive.infomaniak.com/app/share/1543292/0c724738-fba6-49ea-8b32-e34afca1b985

**Comment by luisbocanegra** [comment]
Thanks for the clarification @laichiaheng, looks like mpvqt or libmpv don't support this. A bug report needs to be filled in https://bugs.kde.org/enter_bug.cgi?product=MpvQt to see if they can add support for it

**Comment by laichiaheng** [comment]
> Thanks for the clarification [@laichiaheng](https://github.com/laichiaheng), looks like mpvqt or libmpv don't support this. A bug report needs to be filled in https://bugs.kde.org/enter_bug.cgi?product=MpvQt to see if they can add support for it

https://bugs.kde.org/show_bug.cgi?id=505297
Done. I hope that there will be somebody sees it.

**Comment by herzane52** [comment]
How exactly is this problem solved? I updated to version 2.3.2. But there was no problem. I even used it for 3 days.

![Image](https://github.com/user-attachments/assets/ce8d6944-4988-4c7c-be24-66f83cd7a0cb)

**Comment by Yopioko** [comment]
@Sobtrax  @bronco74 @herzane52 _IT WAS NOT FIXED_,but if you need the fix ,just go as instructed,but instead usual git clone, you should use:

```
git clone -b mpvqt-plugin https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn.git
cd plasma-smart-video-wallpaper-reborn
./install.sh
```
u will have option of using experimental mpvqt plugin feature,and it should fix it,but problem not with the program,but with mesa driver as i understood it.
If u don't want install experimental feature,downgrade to mesa driver  lower than 25.1.0.

**Comment by bronco74** [comment]
Yes that fixed it, but only after enabling MpvQt (Experimental) under
section Playback.

Thanks Yopioko.

Op za 28 jun 2025 om 20:58 schreef Yopioko ***@***.***>:

**Comment by luisbocanegra** [comment]
https://wiki.archlinux.org/title/Environment_variables

or plasma specific: https://wiki.archlinux.org/title/Environment_variables

**Comment by laichiaheng** [comment]
Has it been solved yet?

**Comment by tusx** [comment]
This issue still seems to be present in the latest SteamOS release:

SteamOS 3.8.11
Build: 20260620.1
Released: Jun 19, 2026

Setting the environment variable fixes the issue for now:

```bash
QT_DISABLE_HW_TEXTURES_CONVERSION=1
```

Leaving this here in case anyone else runs into the same problem after the update.

**Comment by AlmighalX** [comment]
Will there ever be a fix without having to touch anything?

**Comment by luisbocanegra** [comment]
> Will there ever be a fix without having to touch anything?


This bug has been fixed already in newer versions of Qt, if you can't update to a newer version because your distribution doesn't provide it the environment variable is the easiest way to fix this.

**Comment by AlmighalX** [comment]
I'm on steam deck

**Comment by rex97k** [comment]
Stumbled on to this thread when fixing the issue on SteamOS. ~/.config/plasma-workspace/env did not work (I suspect Valve has blocked that? The environment variables were not sticking)
The following worked:
1. Run in Konsole: sudo nano /etc/environment
2. Type only: QT_DISABLE_HW_TEXTURES_CONVERSION=1
3. Press Ctrl+O then Enter to save, and Ctrl+X to exit Nano
4. Restart

**Comment by luisbocanegra** [comment]
~~https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/pull/231~~ released in [v2.15.0](https://github.com/luisbocanegra/plasma-smart-video-wallpaper-reborn/releases/tag/v2.15.0) adds a setting for `QT_DISABLE_HW_TEXTURES_CONVERSION`

Can someone try it and let me know if it works?

If after removing the environment variable and restarting there are still green lines open the wallpaper plugin settings and in the Advanced tab scroll to the end and check **Disable hardware textures conversion** then log out and back in.

**Comment by luisbocanegra** [comment]
By the way `QT_DISABLE_HW_TEXTURES_CONVERSION=1` also gets rid of the following warnings that otherwise will spam the journal:

When NVIDIA is the primary GPU and Intel is the one used for VA-API decoding

```
eglCreateImage failed for plane 0 with error code 12300
```

When Intel is the primary GPU and NVIDIA is used for VA-API decoding through <https://github.com/elFarto/nvidia-vaapi-driver/>:

```
vaExportSurfaceHandle failed
```
